#DataSource Configuration
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

  security:
    user:
      name: fkaya
      password: 123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop